CREATE TABLE IF NOT EXISTS calculation_line_geometry (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  version_id BIGINT UNSIGNED NOT NULL,
  line_id BIGINT UNSIGNED NOT NULL,
  position_ref VARCHAR(128) NULL,
  width_mm DECIMAL(19,4) NULL,
  height_mm DECIMAL(19,4) NULL,
  quantity DECIMAL(19,4) NOT NULL DEFAULT 1,
  source_type ENUM('document','drawing','window_schedule','sparingsmeter','manual','other') NOT NULL DEFAULT 'manual',
  source_document_id BIGINT UNSIGNED NULL,
  confidence DECIMAL(6,5) NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY uq_line_geometry (version_id, line_id),
  KEY idx_geometry_version (version_id),
  KEY idx_geometry_position (position_ref),
  CONSTRAINT fk_geometry_version FOREIGN KEY (version_id) REFERENCES calculation_versions(id) ON DELETE CASCADE,
  CONSTRAINT fk_geometry_line FOREIGN KEY (line_id) REFERENCES calculation_lines(id) ON DELETE CASCADE,
  CONSTRAINT chk_geometry_width CHECK (width_mm IS NULL OR width_mm > 0),
  CONSTRAINT chk_geometry_height CHECK (height_mm IS NULL OR height_mm > 0),
  CONSTRAINT chk_geometry_quantity CHECK (quantity > 0),
  CONSTRAINT chk_geometry_confidence CHECK (confidence IS NULL OR (confidence >= 0 AND confidence <= 1))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
