CREATE TABLE IF NOT EXISTS calculation_cutting_profiles (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  profile_ref VARCHAR(128) NOT NULL,
  description VARCHAR(255) NOT NULL,
  stock_lengths_mm JSON NOT NULL,
  kerf_mm DECIMAL(19,4) NOT NULL DEFAULT 3,
  end_trim_mm DECIMAL(19,4) NOT NULL DEFAULT 0,
  min_reusable_remnant_mm DECIMAL(19,4) NOT NULL DEFAULT 300,
  max_practical_stock_length_mm DECIMAL(19,4) NULL,
  practical_waste_tolerance_pct DECIMAL(9,4) NOT NULL DEFAULT 3,
  production_mode ENUM('workshop','site','either') NOT NULL DEFAULT 'either',
  preferred_stock_length_mm DECIMAL(19,4) NULL,
  bundle_by ENUM('position','dwelling','facade','work_package','none') NOT NULL DEFAULT 'position',
  label_required TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY uq_cutting_profile_ref (profile_ref),
  CONSTRAINT chk_cutting_kerf CHECK (kerf_mm >= 0),
  CONSTRAINT chk_cutting_trim CHECK (end_trim_mm >= 0),
  CONSTRAINT chk_cutting_remnant CHECK (min_reusable_remnant_mm >= 0),
  CONSTRAINT chk_cutting_max_practical CHECK (max_practical_stock_length_mm IS NULL OR max_practical_stock_length_mm > 0),
  CONSTRAINT chk_cutting_waste_tolerance CHECK (practical_waste_tolerance_pct >= 0 AND practical_waste_tolerance_pct <= 1000),
  CONSTRAINT chk_cutting_preferred_stock CHECK (preferred_stock_length_mm IS NULL OR preferred_stock_length_mm > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS calculation_cutting_requirements (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  version_id BIGINT UNSIGNED NOT NULL,
  profile_ref VARCHAR(128) NOT NULL,
  source_line_id BIGINT UNSIGNED NULL,
  group_ref VARCHAR(128) NULL,
  position_ref VARCHAR(128) NULL,
  destination_ref VARCHAR(128) NULL,
  production_mode ENUM('workshop','site','either') NOT NULL DEFAULT 'either',
  piece_length_mm DECIMAL(19,4) NOT NULL,
  quantity INT UNSIGNED NOT NULL DEFAULT 1,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  KEY idx_cutting_req_version_profile (version_id, profile_ref),
  KEY idx_cutting_req_group (group_ref),
  KEY idx_cutting_req_destination (destination_ref),
  CONSTRAINT fk_cutting_req_version FOREIGN KEY (version_id) REFERENCES calculation_versions(id) ON DELETE CASCADE,
  CONSTRAINT fk_cutting_req_source_line FOREIGN KEY (source_line_id) REFERENCES calculation_lines(id) ON DELETE SET NULL,
  CONSTRAINT chk_cutting_piece_length CHECK (piece_length_mm > 0),
  CONSTRAINT chk_cutting_quantity CHECK (quantity > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
